// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RulesetEntry struct {
	Path                 string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              string     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Ruleset              *Ruleset   `protobuf:"bytes,3,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	Signature            *Signature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Versions             *Versions  `protobuf:"bytes,5,opt,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RulesetEntry) Reset()         { *m = RulesetEntry{} }
func (m *RulesetEntry) String() string { return proto.CompactTextString(m) }
func (*RulesetEntry) ProtoMessage()    {}
func (*RulesetEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{0}
}
func (m *RulesetEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RulesetEntry.Unmarshal(m, b)
}
func (m *RulesetEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RulesetEntry.Marshal(b, m, deterministic)
}
func (dst *RulesetEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RulesetEntry.Merge(dst, src)
}
func (m *RulesetEntry) XXX_Size() int {
	return xxx_messageInfo_RulesetEntry.Size(m)
}
func (m *RulesetEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_RulesetEntry.DiscardUnknown(m)
}

var xxx_messageInfo_RulesetEntry proto.InternalMessageInfo

func (m *RulesetEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RulesetEntry) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RulesetEntry) GetRuleset() *Ruleset {
	if m != nil {
		return m.Ruleset
	}
	return nil
}

func (m *RulesetEntry) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *RulesetEntry) GetVersions() *Versions {
	if m != nil {
		return m.Versions
	}
	return nil
}

type Ruleset struct {
	Rules                []*Rule  `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ruleset) Reset()         { *m = Ruleset{} }
func (m *Ruleset) String() string { return proto.CompactTextString(m) }
func (*Ruleset) ProtoMessage()    {}
func (*Ruleset) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{1}
}
func (m *Ruleset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ruleset.Unmarshal(m, b)
}
func (m *Ruleset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ruleset.Marshal(b, m, deterministic)
}
func (dst *Ruleset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ruleset.Merge(dst, src)
}
func (m *Ruleset) XXX_Size() int {
	return xxx_messageInfo_Ruleset.Size(m)
}
func (m *Ruleset) XXX_DiscardUnknown() {
	xxx_messageInfo_Ruleset.DiscardUnknown(m)
}

var xxx_messageInfo_Ruleset proto.InternalMessageInfo

func (m *Ruleset) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Ruleset) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Rule struct {
	Expr                 *Expr    `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Result               *Value   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{2}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetExpr() *Expr {
	if m != nil {
		return m.Expr
	}
	return nil
}

func (m *Rule) GetResult() *Value {
	if m != nil {
		return m.Result
	}
	return nil
}

type Expr struct {
	// Types that are valid to be assigned to Expr:
	//	*Expr_Value
	//	*Expr_Param
	//	*Expr_Operator
	Expr                 isExpr_Expr `protobuf_oneof:"expr"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Expr) Reset()         { *m = Expr{} }
func (m *Expr) String() string { return proto.CompactTextString(m) }
func (*Expr) ProtoMessage()    {}
func (*Expr) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{3}
}
func (m *Expr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expr.Unmarshal(m, b)
}
func (m *Expr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expr.Marshal(b, m, deterministic)
}
func (dst *Expr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expr.Merge(dst, src)
}
func (m *Expr) XXX_Size() int {
	return xxx_messageInfo_Expr.Size(m)
}
func (m *Expr) XXX_DiscardUnknown() {
	xxx_messageInfo_Expr.DiscardUnknown(m)
}

var xxx_messageInfo_Expr proto.InternalMessageInfo

type isExpr_Expr interface {
	isExpr_Expr()
}

type Expr_Value struct {
	Value *Value `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type Expr_Param struct {
	Param *Param `protobuf:"bytes,2,opt,name=param,proto3,oneof"`
}

type Expr_Operator struct {
	Operator *Operator `protobuf:"bytes,3,opt,name=operator,proto3,oneof"`
}

func (*Expr_Value) isExpr_Expr() {}

func (*Expr_Param) isExpr_Expr() {}

func (*Expr_Operator) isExpr_Expr() {}

func (m *Expr) GetExpr() isExpr_Expr {
	if m != nil {
		return m.Expr
	}
	return nil
}

func (m *Expr) GetValue() *Value {
	if x, ok := m.GetExpr().(*Expr_Value); ok {
		return x.Value
	}
	return nil
}

func (m *Expr) GetParam() *Param {
	if x, ok := m.GetExpr().(*Expr_Param); ok {
		return x.Param
	}
	return nil
}

func (m *Expr) GetOperator() *Operator {
	if x, ok := m.GetExpr().(*Expr_Operator); ok {
		return x.Operator
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Expr) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Expr_OneofMarshaler, _Expr_OneofUnmarshaler, _Expr_OneofSizer, []interface{}{
		(*Expr_Value)(nil),
		(*Expr_Param)(nil),
		(*Expr_Operator)(nil),
	}
}

func _Expr_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Expr)
	// expr
	switch x := m.Expr.(type) {
	case *Expr_Value:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Value); err != nil {
			return err
		}
	case *Expr_Param:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Param); err != nil {
			return err
		}
	case *Expr_Operator:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Operator); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Expr.Expr has unexpected type %T", x)
	}
	return nil
}

func _Expr_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Expr)
	switch tag {
	case 1: // expr.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Value)
		err := b.DecodeMessage(msg)
		m.Expr = &Expr_Value{msg}
		return true, err
	case 2: // expr.param
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Param)
		err := b.DecodeMessage(msg)
		m.Expr = &Expr_Param{msg}
		return true, err
	case 3: // expr.operator
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Operator)
		err := b.DecodeMessage(msg)
		m.Expr = &Expr_Operator{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Expr_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Expr)
	// expr
	switch x := m.Expr.(type) {
	case *Expr_Value:
		s := proto.Size(x.Value)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Expr_Param:
		s := proto.Size(x.Param)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Expr_Operator:
		s := proto.Size(x.Operator)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Value struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{4}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Value) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Value) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Param struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{5}
}
func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (dst *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(dst, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Param) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Param) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Operator struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Operands             []*Expr  `protobuf:"bytes,2,rep,name=operands,proto3" json:"operands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{6}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (dst *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(dst, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Operator) GetOperands() []*Expr {
	if m != nil {
		return m.Operands
	}
	return nil
}

type Signature struct {
	ReturnType           string            `protobuf:"bytes,1,opt,name=returnType,proto3" json:"returnType,omitempty"`
	ParamTypes           map[string]string `protobuf:"bytes,2,rep,name=paramTypes,proto3" json:"paramTypes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{7}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetReturnType() string {
	if m != nil {
		return m.ReturnType
	}
	return ""
}

func (m *Signature) GetParamTypes() map[string]string {
	if m != nil {
		return m.ParamTypes
	}
	return nil
}

type Versions struct {
	Versions             []string `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Versions) Reset()         { *m = Versions{} }
func (m *Versions) String() string { return proto.CompactTextString(m) }
func (*Versions) ProtoMessage()    {}
func (*Versions) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_204fdf7d5a8a7798, []int{8}
}
func (m *Versions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Versions.Unmarshal(m, b)
}
func (m *Versions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Versions.Marshal(b, m, deterministic)
}
func (dst *Versions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Versions.Merge(dst, src)
}
func (m *Versions) XXX_Size() int {
	return xxx_messageInfo_Versions.Size(m)
}
func (m *Versions) XXX_DiscardUnknown() {
	xxx_messageInfo_Versions.DiscardUnknown(m)
}

var xxx_messageInfo_Versions proto.InternalMessageInfo

func (m *Versions) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

func init() {
	proto.RegisterType((*RulesetEntry)(nil), "proto.RulesetEntry")
	proto.RegisterType((*Ruleset)(nil), "proto.Ruleset")
	proto.RegisterType((*Rule)(nil), "proto.Rule")
	proto.RegisterType((*Expr)(nil), "proto.Expr")
	proto.RegisterType((*Value)(nil), "proto.Value")
	proto.RegisterType((*Param)(nil), "proto.Param")
	proto.RegisterType((*Operator)(nil), "proto.Operator")
	proto.RegisterType((*Signature)(nil), "proto.Signature")
	proto.RegisterMapType((map[string]string)(nil), "proto.Signature.ParamTypesEntry")
	proto.RegisterType((*Versions)(nil), "proto.Versions")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_204fdf7d5a8a7798) }

var fileDescriptor_types_204fdf7d5a8a7798 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x8a, 0x13, 0x41,
	0x10, 0xde, 0x4e, 0x66, 0x92, 0x4c, 0xcd, 0xe2, 0x2e, 0x85, 0x87, 0x66, 0x0f, 0x1a, 0x1b, 0xd1,
	0x80, 0x98, 0x43, 0xbc, 0x88, 0x20, 0x2c, 0x4a, 0x70, 0x2f, 0xa2, 0xb4, 0xe2, 0xbd, 0x25, 0x8d,
	0x86, 0xcd, 0xce, 0x0c, 0x3d, 0x3d, 0xcb, 0xe6, 0x11, 0x7c, 0x17, 0xdf, 0xc2, 0x17, 0x93, 0xaa,
	0xee, 0x4e, 0x66, 0x43, 0x2e, 0x7b, 0x9a, 0xea, 0xfa, 0xbe, 0xfa, 0xea, 0x77, 0xa0, 0xf4, 0xdb,
	0xc6, 0xb6, 0xf3, 0xc6, 0xd5, 0xbe, 0xc6, 0x9c, 0x3f, 0xea, 0x9f, 0x80, 0x53, 0xdd, 0x6d, 0x6c,
	0x6b, 0xfd, 0xb2, 0xf2, 0x6e, 0x8b, 0x08, 0x59, 0x63, 0xfc, 0x6f, 0x29, 0xa6, 0x62, 0x56, 0x68,
	0xb6, 0x51, 0xc2, 0xf8, 0xd6, 0xba, 0x76, 0x5d, 0x57, 0x72, 0xc0, 0xee, 0xf4, 0xc4, 0x19, 0x8c,
	0x5d, 0x88, 0x96, 0xc3, 0xa9, 0x98, 0x95, 0x8b, 0x47, 0x41, 0x7e, 0x1e, 0x35, 0x75, 0x82, 0x71,
	0x0e, 0x45, 0xbb, 0xfe, 0x55, 0x19, 0xdf, 0x39, 0x2b, 0x33, 0xe6, 0x9e, 0x47, 0xee, 0xb7, 0xe4,
	0xd7, 0x7b, 0x0a, 0xbe, 0x82, 0x49, 0x4c, 0xd2, 0xca, 0x9c, 0xe9, 0x67, 0x91, 0xfe, 0x23, 0xba,
	0xf5, 0x8e, 0xa0, 0x2e, 0x61, 0x1c, 0x13, 0xe2, 0x33, 0xc8, 0x39, 0xa5, 0x14, 0xd3, 0xe1, 0xac,
	0x5c, 0x94, 0xbd, 0x7a, 0x74, 0x40, 0xa8, 0x45, 0x9a, 0x44, 0xec, 0x85, 0x6d, 0xf5, 0x19, 0x32,
	0xa2, 0xe0, 0x53, 0xc8, 0xec, 0x5d, 0xe3, 0xb8, 0xfd, 0x7d, 0xf4, 0xf2, 0xae, 0x71, 0x9a, 0x01,
	0x7c, 0x0e, 0x23, 0x67, 0xdb, 0x6e, 0xe3, 0x39, 0xbc, 0x5c, 0x9c, 0xa6, 0xaa, 0xcc, 0xa6, 0xb3,
	0x3a, 0x62, 0xea, 0x8f, 0x80, 0x6c, 0x19, 0xe8, 0xf9, 0x2d, 0x21, 0x51, 0xf0, 0x1e, 0xfb, 0xea,
	0x44, 0x07, 0x90, 0x58, 0x8d, 0x71, 0xe6, 0xe6, 0x40, 0xf3, 0x2b, 0xf9, 0x88, 0xc5, 0x20, 0xbe,
	0x86, 0x49, 0xdd, 0x58, 0x67, 0x7c, 0xed, 0xe2, 0xb4, 0xd3, 0x48, 0xbe, 0x44, 0xf7, 0xd5, 0x89,
	0xde, 0x51, 0x3e, 0x8c, 0x42, 0x2b, 0xea, 0x23, 0xe4, 0x9c, 0x8e, 0xfa, 0xbe, 0x5e, 0x57, 0xab,
	0xb4, 0x5a, 0xb2, 0x8f, 0xcd, 0x82, 0x7c, 0x2b, 0xe3, 0x0d, 0xe7, 0x28, 0x34, 0xdb, 0x24, 0xc2,
	0xd5, 0x3c, 0x44, 0xa4, 0x32, 0x37, 0x36, 0x89, 0x90, 0xad, 0x3e, 0xc1, 0x24, 0x55, 0x7a, 0x54,
	0xe7, 0x65, 0x6c, 0xb0, 0x5a, 0xb5, 0x72, 0x70, 0x6f, 0x7d, 0xbc, 0x80, 0x1d, 0xa8, 0xfe, 0x0a,
	0x28, 0x76, 0x57, 0x83, 0x4f, 0x00, 0x9c, 0xf5, 0x9d, 0xab, 0xbe, 0x53, 0x11, 0x41, 0xb0, 0xe7,
	0xc1, 0x4b, 0x00, 0x1e, 0x20, 0x3d, 0x92, 0xf0, 0xf4, 0xf0, 0xf6, 0xc2, 0xb0, 0x99, 0xc2, 0x3f,
	0x82, 0xee, 0xc5, 0x5c, 0xbc, 0x87, 0xb3, 0x03, 0x18, 0xcf, 0x61, 0x78, 0x6d, 0xb7, 0x31, 0x1b,
	0x99, 0xf8, 0x38, 0xad, 0x3a, 0x8c, 0x21, 0x3c, 0xde, 0x0d, 0xde, 0x0a, 0xf5, 0x02, 0x26, 0xe9,
	0x68, 0xf1, 0xa2, 0x77, 0xd7, 0x74, 0xa2, 0xc5, 0xfe, 0x8c, 0x7f, 0x8e, 0xb8, 0xa6, 0x37, 0xff,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x10, 0x8f, 0xd6, 0x2b, 0xa9, 0x03, 0x00, 0x00,
}
